// Bilingual copy dictionary
window.COPY = {
  en: {
    nav: { products: 'Products', philosophy: 'Philosophy', changelog: "What's new", download: 'Download' },
    hero: {
      eyebrow: 'A suite for real estate',
      title: ['Three focused tools.', 'One quiet suite.'],
      body: 'Scan, calculate, follow up. Without bloat, without accounts, without distractions.',
      cta: 'Explore the suite',
      secondary: 'See what changed',
      pickLabel: 'Pick a tool',
    },
    products: {
      scan: {
        name: 'Scan',
        tagline: 'Documents, organized.',
        pitch: 'Scan, read, file.',
      },
      calc: {
        name: 'Calc',
        tagline: 'Mortgages, instantly.',
        pitch: 'Model a deal.',
      },
      leads: {
        name: 'Leads',
        tagline: 'A calm CRM.',
        pitch: 'Stay on follow-up.',
      },
    },
    stats: {
      title: 'Running quietly, every day.',
      sub: 'Numbers from the last 30 days.',
      items: [
        { v: 148293, l: 'Documents scanned' },
        { v: 24716, l: 'Scenarios modelled' },
        { v: 9872, l: 'Follow-ups completed' },
        { v: 100, l: '% on-device', suffix: '%' },
      ],
    },
    scan: {
      eyebrow: 'Bricks Scan',
      title: ['Your scans', 'organize themselves.'],
      body: 'Scan a receipt, a contract, a listing. Bricks reads each one, gives it a clear name, and files it in the right folder. No uploads.',
      bullets: [
        { t: 'Auto-Sort', d: 'Every file gets a clear name. You don\u2019t decide.' },
        { t: 'Search inside scans', d: 'Find any word, address, or clause \u2014 instantly.' },
        { t: 'On device, private', d: 'Processed on your iPhone. Nothing leaves it.' },
      ],
      more: 'More about Scan', demoLabel: 'Try it',
      demoPlaceholder: 'Search your scans\u2026',
      docs: [
        { name: '2026 Purchase Agreement \u2014 412 Oak St', folder: 'Contracts', pages: 18 },
        { name: '1127 Ashford \u2014 Inspection Report', folder: 'Inspections', pages: 12 },
        { name: 'Closing Docs \u2014 Morales', folder: 'Closings', pages: 24 },
        { name: 'Comps \u2014 Riverside Q1 2026', folder: 'Research', pages: 6 },
        { name: 'Disclosure \u2014 412 Oak St', folder: 'Contracts', pages: 4 },
        { name: 'HOA Letter \u2014 Morales', folder: 'Closings', pages: 2 },
      ],
    },
    calc: {
      eyebrow: 'Bricks Calc',
      title: ['Model a deal', 'on the spot.'],
      body: 'Monthly payments, down payment, amortization. Compare rate scenarios side by side during a client meeting. Offline.',
      bullets: [
        { t: 'Scenarios', d: 'Compare rate and term side by side.' },
        { t: 'Taxes and PMI', d: 'Real numbers, not estimates.' },
        { t: 'Share as PDF', d: 'Send a clean summary in a tap.' },
      ],
      more: 'More about Calc', demoLabel: 'Try it',
      fields: { price: 'Price', down: 'Down', rate: 'Rate', term: 'Term' },
      result: 'Monthly payment',
      years: 'yr',
    },
    leads: {
      eyebrow: 'Bricks Leads',
      title: ['Never forget', 'to follow up.'],
      body: 'Keep every lead, buyer, and seller in one quiet list. Follow-ups show up the day they\u2019re due. Nothing else.',
      bullets: [
        { t: 'Follow-ups', d: 'Queued by date. One tap to close the loop.' },
        { t: 'Properties', d: 'Attach listings to contacts. Search either way.' },
        { t: 'Schedule', d: 'Showings, calls, and meetings in one view.' },
      ],
      more: 'More about Leads',
      demoLabel: 'Today',
      items: [
        { name: 'Ana Morales', prop: '412 Oak St', note: 'Send disclosure', due: 'Today 10:00', done: false },
        { name: 'Diego Salas', prop: '1127 Ashford', note: 'Schedule showing', due: 'Today 14:30', done: false },
        { name: 'Maria Pineda', prop: 'Riverside 3B', note: 'Call about offer', due: 'Today 16:00', done: false },
        { name: 'Rafael Ortiz', prop: '204 Grove', note: 'Follow up on tour', due: 'Today 17:15', done: true },
      ],
    },
    philosophy: {
      eyebrow: 'Philosophy',
      title: ['Quiet software', 'for a noisy job.'],
      body: 'Bricks apps don\u2019t push notifications, don\u2019t ask for your data, and don\u2019t pretend to be more than they are. Each one does one job. Well.',
      pillars: [
        { t: 'On your device', d: 'Documents, data, and calculations stay local. No uploads. No account required.' },
        { t: 'Built for Apple', d: 'Native on iPhone, iPad, and Mac. Designed to feel like system apps.' },
        { t: 'One job per app', d: 'No dashboards you don\u2019t need. Each tool removes one friction from your day.' },
      ],
    },
    testimonials: {
      eyebrow: 'Used by working agents',
      quotes: [
        { q: 'I find any disclosure or amendment in seconds. It removed a layer of stress from every deal.', n: 'Rosa A.', r: 'Real Estate Agent', c: 'Lima' },
        { q: 'The mortgage calculator alone saves time during every client meeting.', n: 'Bruno A.', r: 'Broker Associate', c: 'Lima' },
        { q: 'It feels like a system app made for real estate. I forget it\u2019s a third-party tool.', n: 'Ines A.', r: 'Independent Agent', c: 'Miami' },
        { q: 'My follow-ups stopped falling through the cracks the week I installed Leads.', n: 'Carla M.', r: 'Senior Agent', c: 'Bogot\u00e1' },
      ],
    },
    changelog: {
      eyebrow: "What's new",
      title: 'Small, steady updates.',
      sub: 'Shipped in the last two months.',
      items: [
        { date: 'Apr 14', tag: 'Scan', title: 'Search inside PDFs', body: 'OCR now runs across attached PDFs, not just new scans.' },
        { date: 'Apr 02', tag: 'Calc', title: 'Amortization chart', body: 'A clean visual of principal vs interest over the life of the loan.' },
        { date: 'Mar 21', tag: 'Leads', title: 'Bulk follow-ups', body: 'Reschedule or complete multiple follow-ups at once.' },
        { date: 'Mar 08', tag: 'Scan', title: 'Auto-Sort V2', body: 'Better folder inference on contracts and closing packets.' },
      ],
    },
    cta: {
      title: ['Three tools.', 'One quiet suite.'],
      sub: 'Free to try. No account. Native on Apple.',
      primary: 'Download on the App Store',
    },
    footer: {
      tag: 'Focused apps for real estate agents on Apple.',
      sections: [
        { h: 'Apps', l: ['Bricks Scan', 'Bricks Calc', 'Bricks Leads'] },
        { h: 'Business', l: ['About', 'Purchase guide', 'hello@bricks.pe'] },
        { h: 'Support', l: ['Contact', 'Vote on features', 'Guides', 'Survey'] },
      ],
      legal: ['Privacy Policy', 'Terms of Service'],
      copyright: '\u00a9 2026 Bricks Apps. Made with care.',
      language: 'Language',
      appearance: 'Appearance',
      light: 'Light',
      dark: 'Dark',
      auto: 'System',
    },
  },
  es: {
    nav: { products: 'Productos', philosophy: 'Filosof\u00eda', changelog: 'Novedades', download: 'Descargar' },
    hero: {
      eyebrow: 'Una suite para bienes ra\u00edces',
      title: ['Tres herramientas.', 'Una suite tranquila.'],
      body: 'Escanea, calcula, da seguimiento. Sin relleno, sin cuentas, sin distracciones.',
      cta: 'Explorar la suite',
      secondary: 'Ver novedades',
      pickLabel: 'Elige una herramienta',
    },
    products: {
      scan: { name: 'Scan', tagline: 'Documentos ordenados.', pitch: 'Escanea, lee, archiva.' },
      calc: { name: 'Calc', tagline: 'Hipotecas al instante.', pitch: 'Modela una oferta.' },
      leads: { name: 'Leads', tagline: 'Un CRM tranquilo.', pitch: 'Mant\u00e9n el seguimiento.' },
    },
    stats: {
      title: 'Funcionando en silencio, cada d\u00eda.',
      sub: 'N\u00fameros de los \u00faltimos 30 d\u00edas.',
      items: [
        { v: 148293, l: 'Documentos escaneados' },
        { v: 24716, l: 'Escenarios modelados' },
        { v: 9872, l: 'Seguimientos completados' },
        { v: 100, l: '% en el dispositivo', suffix: '%' },
      ],
    },
    scan: {
      eyebrow: 'Bricks Scan',
      title: ['Tus escaneos', 'se ordenan solos.'],
      body: 'Escanea un recibo, un contrato, un listado. Bricks lo lee, le pone un nombre claro y lo archiva en la carpeta correcta. Sin subir nada.',
      bullets: [
        { t: 'Auto-Sort', d: 'Cada archivo recibe un nombre claro. No decides t\u00fa.' },
        { t: 'Busca dentro de escaneos', d: 'Encuentra cualquier palabra, direcci\u00f3n o cl\u00e1usula \u2014 al instante.' },
        { t: 'En el dispositivo, privado', d: 'Procesado en tu iPhone. Nada sale de \u00e9l.' },
      ],
      more: 'M\u00e1s sobre Scan', demoLabel: 'Pru\u00e9balo',
      demoPlaceholder: 'Busca en tus escaneos\u2026',
      docs: [
        { name: 'Contrato de compra 2026 \u2014 412 Oak St', folder: 'Contratos', pages: 18 },
        { name: '1127 Ashford \u2014 Informe de inspecci\u00f3n', folder: 'Inspecciones', pages: 12 },
        { name: 'Documentos de cierre \u2014 Morales', folder: 'Cierres', pages: 24 },
        { name: 'Comparables \u2014 Riverside Q1 2026', folder: 'Investigaci\u00f3n', pages: 6 },
        { name: 'Divulgaci\u00f3n \u2014 412 Oak St', folder: 'Contratos', pages: 4 },
        { name: 'Carta HOA \u2014 Morales', folder: 'Cierres', pages: 2 },
      ],
    },
    calc: {
      eyebrow: 'Bricks Calc',
      title: ['Modela una oferta', 'al instante.'],
      body: 'Cuotas mensuales, enganche, amortizaci\u00f3n. Compara escenarios de tasa lado a lado durante una reuni\u00f3n. Sin internet.',
      bullets: [
        { t: 'Escenarios', d: 'Compara tasa y plazo lado a lado.' },
        { t: 'Impuestos y PMI', d: 'N\u00fameros reales, no estimaciones.' },
        { t: 'Comparte como PDF', d: 'Env\u00eda un resumen claro en un toque.' },
      ],
      more: 'M\u00e1s sobre Calc', demoLabel: 'Pru\u00e9balo',
      fields: { price: 'Precio', down: 'Enganche', rate: 'Tasa', term: 'Plazo' },
      result: 'Cuota mensual',
      years: 'a\u00f1os',
    },
    leads: {
      eyebrow: 'Bricks Leads',
      title: ['Nunca olvides', 'dar seguimiento.'],
      body: 'Mant\u00e9n cada lead, comprador y vendedor en una lista tranquila. Los seguimientos aparecen el d\u00eda que toca. Nada m\u00e1s.',
      bullets: [
        { t: 'Seguimientos', d: 'En cola por fecha. Un toque y se cierra.' },
        { t: 'Propiedades', d: 'Adjunta listados a contactos. Busca en ambos sentidos.' },
        { t: 'Agenda', d: 'Visitas, llamadas y reuniones en una sola vista.' },
      ],
      more: 'M\u00e1s sobre Leads',
      demoLabel: 'Hoy',
      items: [
        { name: 'Ana Morales', prop: '412 Oak St', note: 'Enviar divulgaci\u00f3n', due: 'Hoy 10:00', done: false },
        { name: 'Diego Salas', prop: '1127 Ashford', note: 'Agendar visita', due: 'Hoy 14:30', done: false },
        { name: 'Mar\u00eda Pineda', prop: 'Riverside 3B', note: 'Llamar sobre oferta', due: 'Hoy 16:00', done: false },
        { name: 'Rafael Ortiz', prop: '204 Grove', note: 'Seguimiento tras visita', due: 'Hoy 17:15', done: true },
      ],
    },
    philosophy: {
      eyebrow: 'Filosof\u00eda',
      title: ['Software tranquilo', 'para un trabajo ruidoso.'],
      body: 'Las apps de Bricks no mandan notificaciones, no piden tus datos y no pretenden ser m\u00e1s de lo que son. Cada una hace un trabajo. Bien.',
      pillars: [
        { t: 'En tu dispositivo', d: 'Documentos, datos y c\u00e1lculos se quedan en local. Sin subir nada. Sin cuenta.' },
        { t: 'Hecho para Apple', d: 'Nativas en iPhone, iPad y Mac. Se sienten parte del sistema.' },
        { t: 'Un trabajo por app', d: 'Sin paneles que no necesitas. Cada herramienta quita una fricci\u00f3n del d\u00eda.' },
      ],
    },
    testimonials: {
      eyebrow: 'Usado por agentes en activo',
      quotes: [
        { q: 'Encuentro cualquier divulgaci\u00f3n o enmienda en segundos. Quit\u00f3 una capa de estr\u00e9s de cada trato.', n: 'Rosa A.', r: 'Agente Inmobiliaria', c: 'Lima' },
        { q: 'Solo la calculadora de hipotecas ahorra tiempo en cada reuni\u00f3n con clientes.', n: 'Bruno A.', r: 'Agente Asociado', c: 'Lima' },
        { q: 'Se siente como una app del sistema hecha para bienes ra\u00edces. Olvido que es de un tercero.', n: 'In\u00e9s A.', r: 'Agente Independiente', c: 'Miami' },
        { q: 'Mis seguimientos dejaron de caerse la semana que instal\u00e9 Leads.', n: 'Carla M.', r: 'Agente Senior', c: 'Bogot\u00e1' },
      ],
    },
    changelog: {
      eyebrow: 'Novedades',
      title: 'Actualizaciones peque\u00f1as y constantes.',
      sub: 'Publicado en los \u00faltimos dos meses.',
      items: [
        { date: '14 Abr', tag: 'Scan', title: 'Buscar dentro de PDF', body: 'El OCR ahora corre en PDF adjuntos, no solo en escaneos nuevos.' },
        { date: '02 Abr', tag: 'Calc', title: 'Gr\u00e1fico de amortizaci\u00f3n', body: 'Un visual limpio de capital vs inter\u00e9s durante la vida del pr\u00e9stamo.' },
        { date: '21 Mar', tag: 'Leads', title: 'Seguimientos en bloque', body: 'Reagenda o completa varios seguimientos a la vez.' },
        { date: '08 Mar', tag: 'Scan', title: 'Auto-Sort V2', body: 'Mejor inferencia de carpetas en contratos y paquetes de cierre.' },
      ],
    },
    cta: {
      title: ['Tres herramientas.', 'Una suite tranquila.'],
      sub: 'Gratis para empezar. Sin cuenta. Nativa en Apple.',
      primary: 'Descargar en el App Store',
    },
    footer: {
      tag: 'Apps enfocadas para agentes inmobiliarios en Apple.',
      sections: [
        { h: 'Apps', l: ['Bricks Scan', 'Bricks Calc', 'Bricks Leads'] },
        { h: 'Empresa', l: ['Sobre nosotros', 'Gu\u00eda de compra', 'hello@bricks.pe'] },
        { h: 'Soporte', l: ['Contacto', 'Votar funciones', 'Gu\u00edas', 'Encuesta'] },
      ],
      legal: ['Pol\u00edtica de privacidad', 'T\u00e9rminos del servicio'],
      copyright: '\u00a9 2026 Bricks Apps. Hecho con cuidado.',
      language: 'Idioma',
      appearance: 'Apariencia',
      light: 'Claro',
      dark: 'Oscuro',
      auto: 'Sistema',
    },
  },
};

window.ACCENTS = {
  scan:  { light: '#00A6A1', vivid: '#00C7B2' },
  calc:  { light: '#007AFF', vivid: '#2E90FF' },
  leads: { light: '#FF9500', vivid: '#FFAD33' },
};
